#ifndef INC_USER_EEPROM_H
#define INC_USER_EEPROM_H
#include "bird.h"
	#define EE_ADD_CURTIME						0  //min,hr,day
	#define EE_ADD_CURBIRDTYPE				EE_ADD_CURTIME+6	 //curBird.Type
	#define	EE_ADD_MANBIRD						EE_ADD_CURBIRDTYPE+1
	#define EE_ADD_MOTOR_ON						EE_ADD_MANBIRD+16
	#define EE_ADD_MOTOR_OFF					EE_ADD_MOTOR_ON+6
	#define EE_ADD_HEATER_PWM					EE_ADD_MOTOR_OFF+6
	#define EE_ADD_ADJUST_FAN_TEMP		EE_ADD_HEATER_PWM+2
	#define EE_ADD_ADJUST_FAN_HUM			EE_ADD_ADJUST_FAN_TEMP+2
	#define EE_ADD_ADJUST_HEATER_TEMP	EE_ADD_ADJUST_FAN_HUM+2
	#define EE_ADD_ADJUST_HEATER_PWMP	EE_ADD_ADJUST_HEATER_TEMP+2
	#define EE_ADD_CALIB_TEMP					EE_ADD_ADJUST_HEATER_PWMP+2
	#define EE_ADD_CALIB_HUM					EE_ADD_CALIB_TEMP+2
	#define EE_ADD_UPPER_LIMIT_TEMP		EE_ADD_CALIB_HUM+2
	#define EE_ADD_FIRST_TIME					EE_ADD_UPPER_LIMIT_TEMP+2

	
	#define DEFAULT_CURBIRDTYPE		Morgh
	
	#define DEFAULT_MOTORON_SEC			14
	#define DEFAULT_MOTORON_MIN			0		
	#define DEFAULT_MOTORON_HR			0		
	#define DEFAULT_MOTORON_DAY			0		
		
	#define DEFAULT_MOTOROFF_SEC			0
	#define DEFAULT_MOTOROFF_MIN			30		
	#define DEFAULT_MOTOROFF_HR				0		
	#define DEFAULT_MOTOROFF_DAY			0		
	
	#define DEFAULT_HEATER_PWM						1000
	#define DEFAULT_ADJUST_FAN_TEMP				5
	#define DEFAULT_ADJUST_FAN_HUM				25	
	#define DEFAULT_ADJUST_HEATER_TEMP		2	
	#define DEFAULT_ADJUST_HEATER_PWMP		50		//%
	
	#define DEFAULT_CALIB_TEMP	0
	#define DEFAULT_CALIB_HUM		0
	//////////////////////////////////////////////////
	#define DEFAULT_PASSWORD	"1365" //4digit
	#define DEFAULT_UPPER_LIMIT_TEMP	385
	
	#define DEFAULT_BUZZER_TEMP	5
	#define DEFAULT_BUZZER_HUM	60
	/////////////////////////////////////////////////////
	#define TEMP_UPPER_VALUE	600
	#define TEMP_LOWER_VALUE	100

	#define HUM_UPPER_VALUE	1000
	#define HUM_LOWER_VALUE	0
	
	#define DAY_UPPER_VALUE	999
	#define DAY_LOWER_VALUE	1
	
	#define TEMP_ADJUST_UPPER_LIMIT	100	
	#define TEMP_ADJUST_LOWER_LIMIT	0	

	#define HUM_ADJUST_UPPER_LIMIT	100	
	#define HUM_ADJUST_LOWER_LIMIT	0	
	/////////////////////////////////////////////////////
#endif